name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    # 代码风格检查
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    # 安全检查
    - name: Run Gosec Security Scanner
      run:
        # 在自动编译的宿主机中下载gosec
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/securego/gosec
        gosec ./...

    - name: Test
      run: go test -v ./...
